name: Lint

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true

      - name: Tidy dependencies
        run: go mod tidy

      - name: Vet
        run: go vet ./...
        
      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          install-go: false
